#!/usr/bin/env bash
# =============================================================================
# arch-post-pacstrap.sh
# Covers everything from after pacstrap to a booted KDE Plasma desktop
# ready to run arch-gaming-setup.sh
#
# USAGE:
#   Part 1 — run from the LIVE USB (before chroot):
#     bash arch-post-pacstrap.sh live
#
#   Part 2 — run from INSIDE arch-chroot:
#     bash arch-post-pacstrap.sh chroot
#
#   Part 3 — run after first reboot, logged in as your user:
#     bash arch-post-pacstrap.sh postboot
# =============================================================================
 
set -euo pipefail
 
# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
 
info()  { echo -e "\n${CYAN}${BOLD}==> ${RESET}${BOLD}$*${RESET}"; }
ok()    { echo -e "${GREEN}  ✓ $*${RESET}"; }
warn()  { echo -e "${YELLOW}  ! $*${RESET}"; }
die()   { echo -e "${RED}${BOLD}ERROR: $*${RESET}" >&2; exit 1; }
ask()   { echo -e "${YELLOW}${BOLD}[?] $*${RESET}"; }
banner(){ echo -e "\n${BOLD}$*${RESET}\n$(printf '═%.0s' {1..44})${RESET}"; }
 
# ── helpers ───────────────────────────────────────────────────────────────────
confirm() {
    ask "$1 [y/N]"
    read -r R
    [[ $R =~ ^[Yy]$ ]]
}
 
require_root()    { [[ $EUID -eq 0 ]] || die "This section must run as root (inside chroot or with sudo)."; }
require_nonroot() { [[ $EUID -ne 0 ]] || die "This section must run as a normal user, not root."; }
 
# =============================================================================
# PART 1 — LIVE USB  (run before chroot)
# =============================================================================
part_live() {
    require_root
    banner "Part 1 — Live USB setup"
    echo "Run this from the Arch live USB shell."
    echo "Assumes partitions are already mounted:"
    echo "  /mnt       → root partition (ext4)"
    echo "  /mnt/boot  → EFI partition  (FAT32)"
    echo
 
    # ── verify mounts ────────────────────────────────────────────────────────
    info "Verifying mounts"
    mountpoint -q /mnt      || die "/mnt is not mounted. Mount your root partition first."
    mountpoint -q /mnt/boot || die "/mnt/boot is not mounted. Mount your ESP first."
    ok "Both partitions are mounted"
 
    # ── generate fstab ───────────────────────────────────────────────────────
    info "Generating fstab"
 
    if grep -q 'Generated by genfstab' /mnt/etc/fstab 2>/dev/null; then
        warn "fstab already contains generated entries — skipping to avoid duplicates"
        warn "If you want to regenerate: rm /mnt/etc/fstab and re-run this section"
    else
        genfstab -U /mnt >> /mnt/etc/fstab
        ok "fstab written to /mnt/etc/fstab"
    fi
 
    echo
    echo "Contents of /mnt/etc/fstab:"
    cat /mnt/etc/fstab
    echo
 
    # ── copy script into new system ──────────────────────────────────────────
    info "Copying this script into the new system"
    SCRIPT_PATH="$(realpath "$0")"
    cp "$SCRIPT_PATH" /mnt/root/arch-post-pacstrap.sh
    chmod +x /mnt/root/arch-post-pacstrap.sh
    ok "Script copied to /mnt/root/arch-post-pacstrap.sh"
 
    # ── instructions ─────────────────────────────────────────────────────────
    echo
    echo -e "${BOLD}Part 1 complete. Next steps:${RESET}"
    echo
    echo "  1. Enter chroot:"
    echo -e "     ${CYAN}arch-chroot /mnt${RESET}"
    echo
    echo "  2. Inside chroot, run Part 2:"
    echo -e "     ${CYAN}bash /root/arch-post-pacstrap.sh chroot${RESET}"
    echo
}
 
# =============================================================================
# PART 2 — INSIDE CHROOT
# =============================================================================
part_chroot() {
    require_root
    banner "Part 2 — Chroot configuration"
    echo "Run this inside arch-chroot."
    echo
 
    # ── verify we're in chroot ───────────────────────────────────────────────
    if ! grep -q 'Arch Linux' /etc/os-release 2>/dev/null; then
        die "This doesn't look like an Arch install. Are you inside arch-chroot?"
    fi
    ok "Confirmed: running inside Arch chroot"
 
    # ── timezone ─────────────────────────────────────────────────────────────
    info "Timezone setup"
    echo
    echo "Available regions (showing Asia as example):"
    ls /usr/share/zoneinfo/ | head -20
    echo "..."
    ask "Enter your timezone (e.g. Asia/Ho_Chi_Minh, Europe/London, America/New_York):"
    read -r TZ
    [[ -f "/usr/share/zoneinfo/$TZ" ]] || die "Timezone '$TZ' not found in /usr/share/zoneinfo/"
    ln -sf "/usr/share/zoneinfo/$TZ" /etc/localtime
    hwclock --systohc
    ok "Timezone set to $TZ, hardware clock synced"
 
    # ── locale ───────────────────────────────────────────────────────────────
    info "Locale configuration"
    sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
    locale-gen
    echo 'LANG=en_US.UTF-8' > /etc/locale.conf
    ok "Locale set to en_US.UTF-8"
 
    # ── hostname ─────────────────────────────────────────────────────────────
    info "Hostname"
    ask "Enter your desired hostname (e.g. archgaming):"
    read -r HOSTNAME
    [[ -n "$HOSTNAME" ]] || die "Hostname cannot be empty"
    echo "$HOSTNAME" > /etc/hostname
    cat > /tmp/hosts_append << EOF
 
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${HOSTNAME}.localdomain ${HOSTNAME}
EOF
    # avoid duplicates
    if ! grep -q "127.0.1.1.*$HOSTNAME" /etc/hosts 2>/dev/null; then
        cat /tmp/hosts_append >> /etc/hosts
    fi
    rm /tmp/hosts_append
    ok "Hostname set to $HOSTNAME"
 
    # ── root password ────────────────────────────────────────────────────────
    info "Root password"
    warn "Setting root password — enter it twice:"
    passwd
    ok "Root password set"
 
    # ── user account ─────────────────────────────────────────────────────────
    info "User account"
    ask "Enter your username (lowercase, no spaces):"
    read -r USERNAME
    [[ -n "$USERNAME" ]] || die "Username cannot be empty"
 
    if id "$USERNAME" &>/dev/null; then
        ok "User $USERNAME already exists — skipping creation"
    else
        useradd -m -G wheel,audio,video,storage,input,games -s /bin/bash "$USERNAME"
        ok "User $USERNAME created with groups: wheel audio video storage input games"
        warn "Setting password for $USERNAME:"
        passwd "$USERNAME"
    fi
 
    # ── sudo ─────────────────────────────────────────────────────────────────
    info "Enabling sudo for wheel group"
    if grep -q '^%wheel ALL=(ALL:ALL) ALL' /etc/sudoers; then
        ok "wheel group already has sudo access"
    else
        sed -i 's/^# %wheel ALL=(ALL:ALL) ALL$/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers
        ok "wheel group granted sudo access"
    fi
 
    # ── NetworkManager ───────────────────────────────────────────────────────
    info "Enabling NetworkManager"
    systemctl enable NetworkManager
    ok "NetworkManager enabled"
 
    # ── bootloader ───────────────────────────────────────────────────────────
    info "Installing systemd-boot"
    bootctl install
    ok "systemd-boot installed to /boot/EFI/"
    bootctl status | head -5
 
    # ── loader.conf ──────────────────────────────────────────────────────────
    info "Writing loader.conf"
    cat > /boot/loader/loader.conf << 'EOF'
default arch.conf
timeout 3
console-mode max
editor no
EOF
    ok "loader.conf written"
 
    # ── boot entry ───────────────────────────────────────────────────────────
    info "Creating boot entry"
 
    # detect root partition UUID automatically
    ROOT_DEV=$(findmnt -n -o SOURCE /)
    ROOT_UUID=$(blkid -s UUID -o value "$ROOT_DEV")
    [[ -n "$ROOT_UUID" ]] || die "Could not determine root partition UUID from blkid"
    ok "Root partition: $ROOT_DEV"
    ok "Root UUID:      $ROOT_UUID"
 
    # detect CPU microcode
    if [[ -f /boot/intel-ucode.img ]]; then
        UCODE="intel-ucode.img"
        ok "Detected Intel CPU microcode"
    elif [[ -f /boot/amd-ucode.img ]]; then
        UCODE="amd-ucode.img"
        ok "Detected AMD CPU microcode"
    else
        warn "No microcode image found in /boot — installing without it"
        warn "Install intel-ucode or amd-ucode and re-run for security patches"
        UCODE=""
    fi
 
    mkdir -p /boot/loader/entries
 
    {
        echo "title   Arch Linux"
        echo "linux   /vmlinuz-linux"
        [[ -n "$UCODE" ]] && echo "initrd  /$UCODE"
        echo "initrd  /initramfs-linux.img"
        echo "options root=UUID=$ROOT_UUID rw quiet splash"
    } > /boot/loader/entries/arch.conf
 
    ok "Boot entry written to /boot/loader/entries/arch.conf"
    echo
    echo "Contents of arch.conf:"
    cat /boot/loader/entries/arch.conf
 
    # ── verify boot files ────────────────────────────────────────────────────
    info "Verifying boot files"
    MISSING=0
    for f in /boot/vmlinuz-linux /boot/initramfs-linux.img /boot/EFI/systemd/systemd-bootx64.efi; do
        if [[ -f "$f" ]]; then
            ok "Found: $f"
        else
            warn "MISSING: $f"
            MISSING=1
        fi
    done
    [[ -n "$UCODE" && -f "/boot/$UCODE" ]] && ok "Found: /boot/$UCODE"
 
    [[ $MISSING -eq 0 ]] || die "Some boot files are missing — check pacstrap included linux and linux-firmware"
 
    echo
    echo "bootctl list output:"
    bootctl list 2>/dev/null || warn "bootctl list failed — check /boot/loader/entries/arch.conf"
 
    # ── done ─────────────────────────────────────────────────────────────────
    echo
    echo -e "${BOLD}Part 2 complete. Next steps:${RESET}"
    echo
    echo "  1. Exit chroot:"
    echo -e "     ${CYAN}exit${RESET}"
    echo
    echo "  2. Unmount and reboot:"
    echo -e "     ${CYAN}umount -R /mnt${RESET}"
    echo -e "     ${CYAN}reboot${RESET}  ← remove USB when screen goes blank"
    echo
    echo "  3. Log in as: $USERNAME"
    echo
    echo "  4. Copy this script to your home directory and run Part 3:"
    echo -e "     ${CYAN}bash arch-post-pacstrap.sh postboot${RESET}"
    echo
}
